#!/bin/bash

# Version: v0.3


# Part: 1
sudo pacman -Syyu --noconfirm
sudo pacman --noconfirm -S archlinux-keyring
sudo pacman-key --init
sudo pacman --noconfirm -S base-devel git wget curl go sed net-tools neovim lsd mpv expect \
seahorse gnome-keyring axel pass-otp youtube-dl yt-dlp obs-studio jq fzf unzip docker ufw firefox \
firefox-developer-edition wireshark-qt jre-openjdk jdk-openjdk python python-pip bpython code \
keepassxc foliate festival festival-english festival-us xdotool macchanger flatpak

# Part: 2
curl https://raw.githubusercontent.com/FlareXes/dotfiles/main/zshrc >> ~/.zshrc
curl https://raw.githubusercontent.com/FlareXes/dotfiles/main/sxhkdrc >> ~/.config/bspwm/sxhkdrc
echo '// "enable-proposed-api": ["ms-python.python"]' >> ~/.vscode-oss/argv.json

curl https://blackarch.org/strap.sh -o /tmp/strap.sh
chmod +x /tmp/strap.sh && cd /tmp/ && sudo ./strap.sh

curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o /tmp/awscliv2.zip
unzip /tmp/awscliv2.zip -d /tmp/ && cd /tmp/aws/ && sudo ./install

sudo wget https://raw.githubusercontent.com/FlareXes/Micro-Utils/main/bin/fshare -O /usr/local/bin/fshare
sudo chmod +x /usr/local/bin/fshare

sudo wget https://raw.githubusercontent.com/FlareXes/Micro-Utils/main/bin/emofzf -O /usr/local/bin/emofzf
sudo chmod +x /usr/local/bin/emofzf

sudo wget https://raw.githubusercontent.com/FlareXes/Micro-Utils/main/bin/myman -O /usr/local/bin/myman
sudo chmod +x /usr/local/bin/myman

sudo wget https://raw.githubusercontent.com/FlareXes/Micro-Utils/main/bin/ytplay -O /usr/local/bin/ytplay
sudo chmod +x /usr/local/bin/ytplay
sudo sed -i "s/mpv/devour mpv/" /usr/local/bin/ytplay

sudo wget https://raw.githubusercontent.com/pystardust/ytfzf/5cd15046127597ac6230c1f021dc9a5cdfff79d0/ytfzf -O /usr/local/bin/ytfzf
sudo chmod +x /usr/local/bin/ytfzf
sudo sed -i "s/mpv/devour mpv/" /usr/local/bin/ytfzf

sudo wget https://raw.githubusercontent.com/FlareXes/passrofi/main/passrofi -O /usr/local/bin/passrofi
sudo chmod +x /usr/local/bin/passrofi

wget https://raw.githubusercontent.com/FlareXes/check-breach/main/check-breach -O /tmp/check-breach
chmod +x /tmp/check-breach && sudo mv /tmp/check-breach /usr/local/bin/

wget https://github.com/FlareXes/randx/raw/master/bin/randx_unix -O /tmp/randx_unix
chmod +x /tmp/randx_unix && sudo mv /tmp/randx_unix /usr/local/bin/randx

sudo wget https://raw.githubusercontent.com/FlareXes/Micro-Utils/main/systemd-unit/macspoof@.service -O /etc/systemd/system/macspoof@.service
sudo systemctl enable macspoof@wlan0.service

git clone https://github.com/FlareXes/cryptfile.git /tmp/cryptfile
cd /tmp/cryptfile && chmod +x setup && ./setup

git clone https://github.com/FlareXes/offsync /tmp/offsync
cd /tmp/offsync && chmod +x ./setup.sh && ./setup.sh

git clone https://github.com/FlareXes/watodo.git /tmp/watodo
cd /tmp/watodo && chmod +x setup && ./setup

git clone https://github.com/FlareXes/watodo-sync.git /tmp/watodo-sync
cd /tmp/watodo-sync && chmod +x setup && ./setup

git clone https://github.com/FlareXes/yt-like.git /tmp/yt-like
cd /tmp/yt-like && chmod +x setup.sh && ./setup.sh

git clone https://github.com/FlareXes/dotfiles.git $HOME/dotfiles
cd $HOME/dotfiles && mv ./.scripts $HOME/

git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1
sed -i "s/transparency = false/transparency = true/" ~/.config/nvim/lua/core/default_config.lua

git clone https://aur.archlinux.org/yay.git /tmp/yay
cd /tmp/yay && makepkg -sirc --noconfirm


# Part: 3
# Wireshark
sudo chmod +x /usr/sbin/dumpcap /usr/bin/dumpcap

# Docker
sudo systemctl start docker.service
sudo systemctl enable docker.service
sudo systemctl restart docker
sudo usermod -aG docker $USER
sudo docker run hello-world


# Ufw
sudo systemctl enable ufw
sudo systemctl start ufw
sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw enable


# Part: 4
sudo pacman --noconfirm -S hashid hashcat johnny feroxbuster nmap seclists \
whois binwalk burpsuite


# Part: 5
yay -S brave-bin librewolf-bin onlyoffice-bin appimagelauncher  portmaster-stub-bin  \
timeshift devour pup --noconfirm


# Part: 6
flatpak install flathub com.jetbrains.PyCharm-Professional -y
flatpak install flathub com.jetbrains.CLion -y
flatpak install flathub com.github.tchx84.Flatseal -y

exit
