#!/bin/bash

# Version: v0.4

if [ ! -f ~/.config/arch-hackset/after_restart ];
then
    # Part: 1
    sudo pacman -Syyu --noconfirm --disable-download-timeout
    sudo pacman --noconfirm -S archlinux-keyring
    sudo pacman-key --init
    sudo pacman --disable-download-timeout --noconfirm -S base-devel git wget curl go sed net-tools neovim lsd mpv expect \
    seahorse axel pass-otp youtube-dl yt-dlp obs-studio jq fzf unzip docker ufw firefox \
    firefox-developer-edition wireshark-qt jre-openjdk jdk-openjdk python python-pip bpython code \
    keepassxc foliate xdotool macchanger flatpak

    # Part: 2
    curl https://raw.githubusercontent.com/FlareXes/dotfiles/main/zshrc >> ~/.zshrc
    curl https://raw.githubusercontent.com/FlareXes/dotfiles/main/sxhkdrc >> ~/.config/bspwm/sxhkdrc

    curl https://blackarch.org/strap.sh -o /tmp/strap.sh
    chmod +x /tmp/strap.sh && cd /tmp/ && sudo ./strap.sh

    curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o /tmp/awscliv2.zip
    unzip /tmp/awscliv2.zip -d /tmp/ && cd /tmp/aws/ && sudo ./install

    sudo wget https://raw.githubusercontent.com/FlareXes/Micro-Utils/main/bin/fshare -O /usr/local/bin/fshare
    sudo chmod +x /usr/local/bin/fshare

    sudo wget https://raw.githubusercontent.com/FlareXes/Micro-Utils/main/bin/emofzf -O /usr/local/bin/emofzf
    sudo chmod +x /usr/local/bin/emofzf

    sudo wget https://raw.githubusercontent.com/FlareXes/Micro-Utils/main/bin/myman -O /usr/local/bin/myman
    sudo chmod +x /usr/local/bin/myman

    sudo wget https://raw.githubusercontent.com/FlareXes/Micro-Utils/main/bin/ytplay -O /usr/local/bin/ytplay
    sudo chmod +x /usr/local/bin/ytplay
    sudo sed -i "s/mpv/devour mpv/" /usr/local/bin/ytplay

    sudo wget https://raw.githubusercontent.com/pystardust/ytfzf/5cd15046127597ac6230c1f021dc9a5cdfff79d0/ytfzf -O /usr/local/bin/ytfzf
    sudo chmod +x /usr/local/bin/ytfzf
    sudo sed -i "s/mpv/devour mpv/" /usr/local/bin/ytfzf

    sudo wget https://raw.githubusercontent.com/FlareXes/passrofi/main/passrofi -O /usr/local/bin/passrofi
    sudo chmod +x /usr/local/bin/passrofi

    wget https://raw.githubusercontent.com/FlareXes/check-breach/main/check-breach -O /tmp/check-breach
    chmod +x /tmp/check-breach && sudo mv /tmp/check-breach /usr/local/bin/

    wget https://github.com/FlareXes/randx/raw/master/bin/randx_unix -O /tmp/randx_unix
    chmod +x /tmp/randx_unix && sudo mv /tmp/randx_unix /usr/local/bin/randx

    sudo wget https://raw.githubusercontent.com/FlareXes/Micro-Utils/main/systemd-unit/macspoof@.service -O /etc/systemd/system/macspoof@.service
    sudo systemctl enable macspoof@wlan0.service

    git clone https://github.com/FlareXes/cryptfile.git /tmp/cryptfile
    cd /tmp/cryptfile && chmod +x setup && ./setup

    git clone https://github.com/FlareXes/offsync /tmp/offsync
    cd /tmp/offsync && chmod +x ./setup.sh && ./setup.sh

    git clone https://github.com/FlareXes/watodo.git /tmp/watodo
    cd /tmp/watodo && chmod +x setup && ./setup

    git clone https://github.com/FlareXes/watodo-sync.git /tmp/watodo-sync
    cd /tmp/watodo-sync && chmod +x setup && ./setup

    git clone https://github.com/FlareXes/yt-like.git /tmp/yt-like
    cd /tmp/yt-like && chmod +x setup.sh && ./setup.sh

    git clone https://github.com/FlareXes/dotfiles.git $HOME/dotfiles
    cd $HOME/dotfiles && mv ./.scripts $HOME/

    git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1
    sed -i "s/transparency = false/transparency = true/" ~/.config/nvim/lua/core/default_config.lua

    git clone https://aur.archlinux.org/yay.git /tmp/yay
    cd /tmp/yay && makepkg -sirc --noconfirm

    git clone https://aur.archlinux.org/snapd.git /tmp/snapd
    cd /tmp/snapd && makepkg -sirc --noconfirm

    # Part: 3
    # Snap
    sudo systemctl enable --now snapd.socket
    sudo systemctl start snapd.service
    sudo ln -s /var/lib/snapd/snap /snap
    sudo systemctl enable --now snapd.apparmor


    # Docker
    sudo systemctl start docker.service
    sudo systemctl enable docker.service
    sudo systemctl restart docker
    sudo usermod -aG docker $USER
    sudo docker run hello-world


    # Ufw
    sudo systemctl enable ufw
    sudo systemctl start ufw
    sudo ufw default allow outgoing
    sudo ufw default deny incoming
    sudo ufw enable


    ## System Restart ##
    mkdir -p ~/.config/arch-hackset && touch ~/.config/arch-hackset/after_restart
    sleep 5
    reboot

else

    # Miscellaneous
    sudo chmod +x /usr/sbin/dumpcap /usr/bin/dumpcap
    sudo systemctl enable --now snapd.apparmor

    # Part: 4
    sudo pacman --disable-download-timeout --noconfirm -S hashid hashcat johnny feroxbuster nmap seclists \
    whois binwalk burpsuite


    # Part: 5
    yay -S brave-bin librewolf-bin onlyoffice-bin appimagelauncher portmaster-stub-bin  \
    timeshift devour pup --noconfirm


    # Part: 6
    sudo snap install pycharm-professional --classic
    sudo snap install clion --classic
    sudo snap install authy

    # Part: 7
    rm -rf ~/.config/arch-hackset/
fi

exit
