#!/bin/sh

# Version: 2.1

function isexists {
    local FLAG=1
    if ! command -v $1 &> /dev/null
    then
        FLAG=0
    fi
    echo $FLAG
}


function greenecho {
    local GREEN='\033[1;32m'
    local NOCOLOR='\033[0m'
    echo -e "\n\n${GREEN}$*${NOCOLOR}"
}

function snapd {
    git clone https://aur.archlinux.org/snapd.git /tmp/snapd
    cd /tmp/snapd && makepkg -si
    sudo systemctl enable --now snapd.socket
    sudo systemctl start snapd.service
    sudo ln -s /var/lib/snapd/snap /snap
}

function restart_alert {
    echo -e "\n\nSystem About To Restart In 10 Seconds. Save Your Work Now!"
    sleep 10
    reboot
}



########################################################################################
########################################################################################
########################################################################################



# Clean Odd File ANd Directories
sudo rm -rfv /tmp/yay /tmp/snapd /tmp/aws /tmp/awscliv2.zip
sudo rm -rfv /usr/local/bin/gobuster /usr/local/bin/ffuf /usr/local/bin/ytfzf /usr/local/bin/fshare

# Initial Setup
greenecho Initial Setup In Progress
sudo pacman-key --init
sudo pacman -Syyu --noconfirm
sudo pacman -S base-devel git go wget curl xclip jq fzf --noconfirm

# Snap
greenecho Snap Installation
if [ $( isexists snap ) == 0 ]
then
    read -p "Snap is required system reboot. Reboot after installation (y/n): " CHOICE
    if [ $CHOICE == "y" ] || [ $CHOICE == "Y" ]
    then
        snapd
        restart_alert
    fi
fi

# Yay
greenecho Yay Installation
if [ $( isexists yay ) == 0 ]
then
    git clone https://aur.archlinux.org/yay.git /tmp/yay
    cd /tmp/yay && makepkg -si && yay --noconfirm
fi

# BlackArch Repository
greenecho BlackArch Repository Setup
curl https://blackarch.org/strap.sh -o /tmp/strap.sh
sudo chmod +x /tmp/strap.sh
sudo /bin/sh /tmp/strap.sh
sudo pacman -Syyu --noconfirm



########################################################################################
########################################################################################
########################################################################################



# Gobuster
greenecho Gobuster Installation
if [ $( isexists gobuster ) == 0 ]
then
    sudo pacman -S gobuster --noconfirm
fi

# Ffuf
greenecho Ffuf Installation
if [ $( isexists ffuf ) == 0 ]
then
    sudo pacman -S ffuf --noconfirm
fi

# Ltrace
greenecho Ltrace Installation
if [ $( isexists ltrace ) == 0 ]
then
    sudo pacman -S ltrace --noconfirm
fi

# Ghidra
greenecho Ghidra Installation
if [ $( isexists ghidra ) == 0 ]
then
    sudo pacman -S ghidra --noconfirm
fi

# John The Ripper
greenecho John The Ripper Installation
if [ $( isexists john ) == 0 ]
then
    sudo pacman -S john --noconfirm
fi

# Hashcat
greenecho Hashcat Installation
if [ $( isexists hashcat ) == 0 ]
then
    sudo pacman -S hashcat --noconfirm
fi

# Binwalk
greenecho Binwalk Installation
if [ $( isexists binwalk ) == 0 ]
then
    sudo pacman -S binwalk --noconfirm
fi

# Wireshark
greenecho Wireshark Installation
if [ $( isexists wireshark ) == 0 ]
then
    sudo pacman -S wireshark-qt --noconfirm
    sudo chmod +x /usr/sbin/dumpcap
    chmod +x /usr/bin/dumpcap
fi

# Exiftool
greenecho ExifTool Installation
if [ $( isexists exiftool ) == 0 ]
then
    sudo pacman -S perl-image-exiftool --noconfirm
fi


########################################################################################
########################################################################################
########################################################################################



# Ufw 
greenecho UFW Installation
if [ $( isexists ufw ) == 0 ]
then
    sudo pacman -S ufw --noconfirm
fi
sudo systemctl start ufw
sudo systemctl enable ufw
sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw enable

# Authy
greenecho Authy Installation
if [ $( isexists authy ) == 0 ]
then
    sudo snap install authy
fi



########################################################################################
########################################################################################
########################################################################################



# Timeshift
greenecho Timeshift Installation
if [ $( isexists timeshift ) == 0 ]
then
    yay -S timeshift --noconfirm
fi

# Docker
greenecho Docker Installation
if [ $( isexists docker ) == 0 ]
then
    sudo pacman -S docker --noconfirm
fi
sudo systemctl start docker.service
sudo systemctl enable docker.service
sudo systemctl restart docker
sudo usermod -aG docker $USER
echo -e "\nTesting Docker Installation Via 'hello-world' Image"
sudo docker run hello-world

# Aws Cli
greenecho AWS-CLI Installation
if [ $( isexists aws ) == 0 ]
then
    curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o /tmp/awscliv2.zip
    unzip /tmp/awscliv2.zip -d /tmp/
    sudo /tmp/aws/install
fi



########################################################################################
########################################################################################
########################################################################################



# Neovim
greenecho Neovim Installation
if [ $( isexists neovim ) == 0 ]
then
    sudo pacman -S neovim --noconfirm
fi

# Lsd
# greenecho Lsd Installation
sudo pacman -S lsd
echo -e "\n# ls" >> ~/.zshrc
if alias l 2>/dev/null; then
  echo "alias l='lsd -l'" >> ~/.zshrc
fi

if alias ll 2>/dev/null; then
  echo "alias ll='lsd -la'" >> ~/.zshrc
fi

if alias la 2>/dev/null; then
  echo "alias la='lsd -A'" >> ~/.zshrc
fi



########################################################################################
########################################################################################
########################################################################################



# Visual Stdio Code
greenecho Visual Stdio Code Installation
if [ $( isexists code ) == 0 ]
then
    sudo snap install code --classic
fi

# GDB :- GNU Debugger
greenecho GDB Installation
if [ $( isexists gdb ) == 0 ]
then
    sudo pacman -S gdb --noconfirm
fi


########################################################################################
########################################################################################
########################################################################################



# Brave
greenecho Brave Installation
if [ $( isexists brave ) == 0 ]
then
    yay -S brave-bin --noconfirm
fi

# Librewolf
greenecho Librewolf Installation
if [ $( isexists librewolf ) == 0 ]
then
    yay -S librewolf-bin --noconfirm
fi

# MPV
greenecho Mpv Installation
if [ $( isexists mpv ) == 0 ]
then
    sudo pacman -S mpv --noconfirm
fi

# Devour
greenecho Devour Installation
if [ $( isexists devour ) == 0 ]
then
    yay -S devour --noconfirm
    echo 'alias mpv="devour mpv"' >> ~/.zshrc
    echo 'alias mpv="devour mpv"' >> ~/.bashrc
fi

# Fshare
greenecho Creating Fshare Utility
sudo wget https://raw.githubusercontent.com/FlareXes/Mirco-Utils/main/fshare -O /usr/local/bin/fshare
sudo chmod +x /usr/local/bin/fshare

# Ytfzf
greenecho Ytfzf Installation
if [ $( isexists pup ) == 0 ]
then
    yay -S pup --noconfirm
    sudo wget https://raw.githubusercontent.com/pystardust/ytfzf/5cd15046127597ac6230c1f021dc9a5cdfff79d0/ytfzf -O /usr/local/bin/ytfzf
    sudo chmod +x /usr/local/bin/ytfzf
fi

# YouTube-dl And Yt-Dlp
greenecho YouTube-dl And yt-dlp Installation
if [ $( isexists yt-dlp ) == 0 ]
then
    sudo pacman -S youtube-dl yt-dlp --noconfirm
fi

echo -e $'\e[32;1m\nInstalltion Complete\e\n'
