#!/bin/sh

# Version: 2.2

function isexists {
    local FLAG=1
    if ! command -v $1 &> /dev/null
    then
        FLAG=0
    fi
    echo $FLAG
}


function greenecho {
    local GREEN='\033[1;32m'
    local NOCOLOR='\033[0m'
    echo -e "\n\n${GREEN}$*${NOCOLOR}"
}

function snapd_setup {
    sudo systemctl enable --now snapd.socket
    sudo systemctl start snapd.service
    sudo ln -s /var/lib/snapd/snap /snap
}

function restart_alert {
    echo -e "\n\nSystem About To Restart In 10 Seconds. Save Your Work Now!"
    sleep 10
    reboot
}


########################################################################################
########################################################################################
########################################################################################


# Clean Odd File ANd Directories
sudo rm -rfv /tmp/yay /tmp/snapd /tmp/aws /tmp/awscliv2.zip
sudo rm -rfv /usr/local/bin/gobuster /usr/local/bin/ffuf /usr/local/bin/ytfzf /usr/local/bin/fshare

# Initial Setup
greenecho Initial Setup In Progress
sudo pacman-key --init
sudo pacman -Syyu --noconfirm
sudo pacman -S base-devel git go wget curl net-tools xclip --noconfirm

# Snap
greenecho Snap Installation
if [ $( isexists snap ) == 0 ];
then
    read -p "Snap is required system reboot. Reboot after installation (y/n): " CHOICE
    if [ $CHOICE == "y" ] || [ $CHOICE == "Y" ];
    then
        git clone https://aur.archlinux.org/snapd.git /tmp/snapd
        cd /tmp/snapd && makepkg -si
        snapd_setup
        restart_alert
    else
        snapd_setup
    fi
fi

# Yay
greenecho Yay Installation
if [ $( isexists yay ) == 0 ]
then
    git clone https://aur.archlinux.org/yay.git /tmp/yay
    cd /tmp/yay && makepkg -si && yay --noconfirm
fi

# BlackArch Repository
greenecho BlackArch Repository Setup
curl https://blackarch.org/strap.sh -o /tmp/strap.sh
sudo chmod +x /tmp/strap.sh
sudo /bin/sh /tmp/strap.sh
sudo pacman -Syyu --noconfirm


########################################################################################
########################################################################################
########################################################################################

# Basics
greenecho Basic Utilities Installation
sudo pacman -S --noconfirm ffuf ltrace ghidra gobuster john hashcat binwalk perl-image-exiftool \
                neovim lsd gdb mpv youtube-dl yt-dlp jq fzf

greenecho Yay Installations
yay -S brave-bin librewolf-bin pup timeshift --noconfirm

# Wireshark
greenecho Wireshark Installation
if [ $( isexists wireshark ) == 0 ]
then
    sudo pacman -S wireshark-qt --noconfirm
    sudo chmod +x /usr/sbin/dumpcap
    chmod +x /usr/bin/dumpcap
fi

# Ufw 
greenecho UFW Installation
if [ $( isexists ufw ) == 0 ]
then
    sudo pacman -S ufw --noconfirm
fi
sudo systemctl start ufw
sudo systemctl enable ufw
sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw enable

# Docker
greenecho Docker Installation
if [ $( isexists docker ) == 0 ]
then
    sudo pacman -S docker --noconfirm
fi
sudo systemctl start docker.service
sudo systemctl enable docker.service
sudo systemctl restart docker
sudo usermod -aG docker $USER
echo -e "\nTesting Docker Installation Via 'hello-world' Image"
sudo docker run hello-world

# Aws Cli
greenecho AWS-CLI Installation
if [ $( isexists aws ) == 0 ]
then
    curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o /tmp/awscliv2.zip
    unzip /tmp/awscliv2.zip -d /tmp/
    sudo /tmp/aws/install
fi

# Authy
greenecho Authy Installation
if [ $( isexists authy ) == 0 ]
then
    sudo snap install authy
fi

# Visual Stdio Code
greenecho Visual Stdio Code Installation
if [ $( isexists code ) == 0 ]
then
    sudo snap install code --classic
fi

# Devour
greenecho Devour Installation
if [ $( isexists devour ) == 0 ]
then
    yay -S devour --noconfirm
    echo 'alias mpv="devour mpv"' >> ~/.zshrc
    echo 'alias mpv="devour mpv"' >> ~/.bashrc
fi

# Fshare
greenecho Creating Fshare Utility
sudo wget https://raw.githubusercontent.com/FlareXes/Mirco-Utils/main/fshare -O /usr/local/bin/fshare
sudo chmod +x /usr/local/bin/fshare

# Ytfzf
greenecho Ytfzf Installation
sudo wget https://raw.githubusercontent.com/pystardust/ytfzf/5cd15046127597ac6230c1f021dc9a5cdfff79d0/ytfzf -O /usr/local/bin/ytfzf
sudo chmod +x /usr/local/bin/ytfzf

echo -e $'\e[32;1m\nInstalltion Complete\e\n'

exit 0